services:
  redis:
    image: redis:7.2.9
    container_name: redis_pied_market
    command: redis-server
    ports:
      - '6378:6379'
    networks:
      net_con:

  rabbitmq:
    container_name: rabbitmq_pied_market
    image: rabbitmq:3.12-management
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSW}
    ports:
      - '5672:5672'
      - '15672:15672'
    dns:
      - 8.8.8.8
      - 1.1.1.1
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      net_con:

  celery_worker:
    container_name: celery_worker_pied_market
    build: .
    command: celery -A core.config_dir.celery_config worker --loglevel=info -Q extended_product_card_queue,mail_queue
    environment:
      - DOCKERIZED=1
      - CELERY_WORKER=1
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    develop:
      watch:
        - target: /app
          path: ./core
          action: sync+restart
    depends_on:
      - rabbitmq
      - redis
    volumes:
      - ./core/templates/images:/app/core/templates/images
    networks:
      net_con:
    extra_hosts:
      - "host.docker.internal:host-gateway"

  smtp_service:
    image: rnwood/smtp4dev
    container_name: smtp4dev_pied_market
    environment:
      - ServerOptions__TlsCertificateFile=${SMTP_CERT_DOCKER}
      - ServerOptions__TlsKeyFile=${SMTP_KEY_DOCKER}
      - ServerOptions__TlsMode=StartTls
    ports:
      - "2525:25"
      - "3000:80"
    networks:
      net_con:

#  es01:
#    container_name: es_pied_market
#    image: elasticsearch:${ELASTIC_VERSION}
#    environment:
#      - node.name=es01
#      - discovery.type=single-node
#      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
#
#      - xpack.security.enabled=false
#      - xpack.security.http.ssl.enabled=false
#      - xpack.security.transport.ssl.enabled=false
#    mem_limit: 3g
#    volumes:
#      - esdata01:/usr/share/elasticsearch/data
#      - ./create_new_cert_p12_elastic:/usr/share/elasticsearch/config/dev_files
#    ports:
#      - '9200:9200'
#    networks:
#      net_con:
#
#  kibana:
#    depends_on:
#      - es01
#    container_name: kibana_pied_market
#    image: kibana:${ELASTIC_VERSION}
#    environment:
#      - ELASTICSEARCH_HOSTS=http://es01:${ELASTIC_PORT}
#    ports:
#      - '5602:5601'
#    networks:
#      net_con:


networks:
  net_con:
    driver: bridge

volumes:
  rabbitmq_data:
    driver: local
  esdata01:
    driver: local
