services:
  pg_db:
    container_name: MarketplaceFastAPI_db
    image: postgres:16
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB}
    restart: on-failure
    ports:
      - '5432:5432'
    networks:
      - net_con
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ./dumps/may_14_marketplace_dump.backup:/docker-entrypoint-initdb/marketplace_db_backup.backup

  marketplace:
    container_name: MarketplaceFastAPI_marketplace
    build: .
    command: python core/main.py
    env_file:
      - ./.env
    depends_on:
      - pg_db
    restart: on-failure

    networks:
      net_con:



networks:
  net_con:
    driver: bridge